Repository AEFeinstein/Super-2024-Swadge-FW, pull requests merged in 2023-08, with the labels that each got.

#30 Fix drawLine() being drawn at incorrect y when dashWidth is non-zero
  main/display/shapes.c
Labels: bug

#34 Mapped menu items
  main/menu/menu.c
  main/menu/menu.h
  main/menu/menuLogbookRenderer.c
  main/modes/mainMenu/mainMenu.c
  main/utils/settingsManager.c
Labels: enhancement

#40 Fix main menu buzzing forever
  main/menu/menu.c
  main/modes/mainMenu/mainMenu.c
Labels: bug

#42 Quick Settings Menu
  assets/quickSettings/backlightDisabled.png
  assets/quickSettings/backlightEnabled.png
  assets/quickSettings/defaultSetting.png
  assets/quickSettings/ledsDisabled.png
  assets/quickSettings/ledsEnabled.png
  assets/quickSettings/musicDisabled.png
  assets/quickSettings/musicEnabled.png
  assets/quickSettings/sfxDisabled.png
  assets/quickSettings/sfxEnabled.png
  main/CMakeLists.txt
  main/menu/menu.c
  main/menu/menuLogbookRenderer.c
  main/menu/menu_utils.c
  main/menu/menu_utils.h
  main/modes/quickSettings/menuQuickSettingsRenderer.c
  main/modes/quickSettings/menuQuickSettingsRenderer.h
  main/modes/quickSettings/quickSettings.c
  main/modes/quickSettings/quickSettings.h
  main/swadge2024.c
Labels: enhancement

#54 Porting docs
  Doxyfile
  docs/PORTING.md
  main/swadge2024.c
Labels: documentation

#57 Add latest rawdraw_sf.h to fix memory leaks
  emulator/src/rawdraw_sf.h
Labels: bug
